apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
spec:
  selector:
    app: grafana-pod
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
